apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myvote-quick-cluster
  region: us-east-1
  version: "1.28"

nodeGroups:
  - name: ng-default
    instanceType: t3.medium
    desiredCapacity: 1
    ssh:
      allow: true
