replicaCount: 1

image:
  repository: ghcr.io/girmaat/my-vote-ui  
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 80

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  timeoutSeconds: 1

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 10
  timeoutSeconds: 1
