apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../../base/argocd

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
      namespace: argocd
    patch: |
      - op: add
        path: /spec/template/metadata/labels/log-collect
        value: "enabled"

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
      namespace: argocd
    patch: |
      - op: add
        path: /spec/template/metadata/labels/log-collect
        value: "enabled"

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-application-controller
      namespace: argocd
    patch: |
      - op: add
        path: /spec/template/metadata/labels/log-collect
        value: "enabled"

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-applicationset-controller
      namespace: argocd
    patch: |
      - op: add
        path: /spec/template/metadata/labels/log-collect
        value: "enabled"

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
      namespace: argocd
    patch: |
      - op: add
        path: /spec/template/metadata/labels/log-collect
        value: "enabled"

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-notifications-controller
      namespace: argocd
    patch: |
      - op: add
        path: /spec/template/metadata/labels/log-collect
        value: "enabled"
