resources:
  - ../../../base/argocd

patches:
  - path: patch-argocd-server.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server

  - path: patch-argocd-repo-server.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server

  - path: patch-argocd-application-controller.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: argocd-application-controller
