apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-vote-api
  labels:
    app: my-vote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-vote-api
  template:
    metadata:
      labels:
        app: my-vote-api
    spec:
      containers:
        - name: my-vote-api
          image: nginx
          ports:
            - containerPort: 80
